In [1]:
import numpy as np
import pandas as pd

In [2]:
file_path = 'dataset2/similarity_network/LSS.npy'

In [3]:
data = np.load(file_path)

In [4]:
data.shape

(711, 711)

In [5]:
excel_file_path = 'dataset2/similarity_network/LGS.xlsx'
df = pd.read_excel(excel_file_path, header=None)

In [6]:
data_array = df.to_numpy()

In [7]:
npy_file_path = 'dataset2/similarity_network/LGS.npy'
np.save(npy_file_path, data_array)

In [8]:
data = np.load(npy_file_path)

In [9]:
data.shape

(711, 711)

In [10]:
excel_file_path = 'dataset2/similarity_network/DGS.xlsx'
df = pd.read_excel(excel_file_path, header=None)
data_array = df.to_numpy()
npy_file_path = 'dataset2/similarity_network/DGS.npy'
np.save(npy_file_path, data_array)

In [11]:
data = np.load(npy_file_path)
data.shape

(330, 330)

In [12]:
matrix1 = np.load('dataset2/similarity_network/LFS.npy')
matrix2 = np.load('dataset2/similarity_network/LGS.npy')
matrix3 = np.load('dataset2/similarity_network/LSS.npy')

In [13]:
average_matrix = (matrix2 + matrix3) / 2
result_matrix = np.maximum(average_matrix, matrix1)

In [14]:
print("Result Matrix:")
print(result_matrix)

Result Matrix:
[[1.         0.15695191 0.28640581 ... 0.51856735 0.31816704 0.20807215]
 [0.15695191 1.         0.46458715 ... 0.31202974 0.49058067 0.60296554]
 [0.28640581 0.46458715 1.         ... 0.31807986 0.26735304 0.41390849]
 ...
 [0.51856735 0.31202974 0.31807986 ... 1.         0.24529013 0.32714934]
 [0.31816704 0.49058067 0.26735304 ... 0.24529013 1.         0.44649397]
 [0.20807215 0.60296554 0.41390849 ... 0.32714934 0.44649397 1.        ]]


In [15]:
np.save('dataset2/similarity_network/LS.npy', result_matrix)

In [16]:
result_matrix.shape

(711, 711)

In [17]:
matrix1 = np.load('dataset2/similarity_network/DSS.npy')
matrix2 = np.load('dataset2/similarity_network/DGS.npy')

In [18]:
matrix1[1,1]

0.0

In [19]:
average_matrix = (matrix1 + matrix2) / 2

In [20]:
print(average_matrix)

[[0.5        0.02959212 0.03395417 ... 0.00817145 0.02558285 0.03395207]
 [0.02959212 0.5        0.03137463 ... 0.00916587 0.01485465 0.03127651]
 [0.03395417 0.03137463 0.5        ... 0.07733396 0.07550513 0.09533178]
 ...
 [0.00817145 0.00916587 0.07733396 ... 0.5        0.45054704 0.45188102]
 [0.02558285 0.01485465 0.07550513 ... 0.45054704 0.5        0.51538462]
 [0.03395207 0.03127651 0.09533178 ... 0.45188102 0.51538462 0.5       ]]


In [22]:
# 将原始矩阵的对角线设置为1
for i in range(min(330, 330)):
    average_matrix[i, i] = 1

In [23]:
print(average_matrix)

[[1.         0.02959212 0.03395417 ... 0.00817145 0.02558285 0.03395207]
 [0.02959212 1.         0.03137463 ... 0.00916587 0.01485465 0.03127651]
 [0.03395417 0.03137463 1.         ... 0.07733396 0.07550513 0.09533178]
 ...
 [0.00817145 0.00916587 0.07733396 ... 1.         0.45054704 0.45188102]
 [0.02558285 0.01485465 0.07550513 ... 0.45054704 1.         0.51538462]
 [0.03395207 0.03127651 0.09533178 ... 0.45188102 0.51538462 1.        ]]


In [24]:
np.save('dataset2/similarity_network/DS.npy', average_matrix)

In [25]:
average_matrix.shape

(330, 330)